### ISSUE TITLE
Out commented code

### ISSUE THREAD

**Issue by Mokerstier** [JimmydeKroon/web-app-from-scratch-2021#8]
https://github.com/JimmydeKroon/web-app-from-scratch-2021/blob/062a0309c6535df0d16bfc25a177785add73bfd6/src/js/spacex.js#L1-L34

Kan dit weg?
Push het liefst alleen werkende code naar git, houd je github "schoon"

**Comment by JimmydeKroon** [comment]
bewaard omdat ik er iets over wilde schrijven in de readme. Staat nu in de readme dus is verwijderd.
